name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t local < .devcontainer/Dockerfile
      - name: Run tests
        run: docker run -it -v $PWD:/srv -w/srv local make test
